//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_CellexalVR : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean TriggerClick
        {
            get
            {
                return SteamVR_Actions.cellexalVR_TriggerClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabGrip
        {
            get
            {
                return SteamVR_Actions.cellexalVR_GrabGrip;
            }
        }
        
        public virtual SteamVR_Action_Boolean UpClick
        {
            get
            {
                return SteamVR_Actions.cellexalVR_UpClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean DownClick
        {
            get
            {
                return SteamVR_Actions.cellexalVR_DownClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightClick
        {
            get
            {
                return SteamVR_Actions.cellexalVR_RightClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftClick
        {
            get
            {
                return SteamVR_Actions.cellexalVR_LeftClick;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.cellexalVR_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.cellexalVR_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.cellexalVR_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Single Squeeze
        {
            get
            {
                return SteamVR_Actions.cellexalVR_Squeeze;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.cellexalVR_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.cellexalVR_Haptic;
            }
        }
    }
}
